// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type ListingEntity = {
    id?: string;
    title?: string | null;
    description?: string | null;
    price?: number;
    status?: number;
};

export type GetApiListingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Listings';
};

export type GetApiListingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiListingsData = {
    body?: ListingEntity;
    path?: never;
    query?: never;
    url: '/api/Listings';
};

export type PostApiListingsResponses = {
    /**
     * OK
     */
    200: unknown;
};
